name: Frontend Continuous Integration
on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main
    paths: starter/frontend

defaults:
  run:
    working-directory: starter/frontend

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node 
        uses: actions/setup-node@v4
        with:
          node-version: latest
          
      - name: install dependancies
        run: npm ci

      - name: Run tests
        run: npm test
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node 
        uses: actions/setup-node@v4
        with:
          node-version: latest
          
      - name: install dependancies
        run: npm ci

      - name: Run tests
        run: npm run lint        
